seed: 0501
exp: mtg_top50
model_name: mert

data:
  dataset:
    manifest_path: metadata/mtg_top50.json
    base_audio_path: ../data/mtg-jamendo-dataset/

    length: 120000
  
  batch_size: 16
  train_shuffle: true
  num_workers: 16

model:
  encoder_dim: 768
  encoder_depth: 6

  freeze_feature: true
  freeze_encoder: true

  model_size: 95M

  optim:
    optimizer:
      name: Adam
      args:
        lr: 0.0001
        weight_decay: 0.0

    scheduler:
      warmup_steps: 0
      max_steps: 100000
      lr_min: 0.0001

trainer:
  args:
    max_epochs: -1
    max_steps: 100000
    gradient_clip_val: 1.0

    limit_train_batches: 2000

    accelerator: gpu
    devices: [0]
    deterministic: false
    precision: bf16-mixed

    check_val_every_n_epoch: 1
    log_every_n_steps: 20

  logger:
    save_dir: &save_dir work_dir/mtg_top50/mert_probe_16_1e-4_0_nowarmup_nodecay
    name: log

  checkpoint:
    dirpath: *save_dir
    filename: epoch={epoch}-mAP={val/mAP:.3f}
    auto_insert_metric_name: false

    save_top_k: 5
    save_last: true

    monitor: val/mAP
    mode: max
    every_n_epochs: 1
