seed: 0501
exp: mtat
model_name: mert

data:
  dataset:
    manifest_path: metadata/mtat_clean.json
    base_audio_path: ../data/MagnaTagATune/

    length: 120000
  
  batch_size: 16
  train_shuffle: true
  num_workers: 16

model:
  encoder_dim: 768
  encoder_depth: 6

  freeze_feature: false
  freeze_encoder: false

  model_size: 95M
  ckpt_path: models/backbone/pytorch_model.bin

  optim:
    optimizer:
      name: Adam
      args:
        lr: 0.00001
        weight_decay: 0.0

    scheduler:
      warmup_steps: 0
      max_steps: 60000
      lr_min: 1.0e-7

trainer:
  args:
    max_epochs: -1
    max_steps: 60000
    gradient_clip_val: 1.0

    accelerator: gpu
    devices: [0]
    deterministic: false
    precision: bf16-mixed

    check_val_every_n_epoch: 1
    log_every_n_steps: 20

  logger:
    save_dir: &save_dir work_dir/mtat_clean/mert_finetune_16_1e-5_0_nowarmup_1e-7
    name: log

  checkpoint:
    dirpath: *save_dir
    filename: epoch={epoch}-mAP={val/mAP:.3f}
    auto_insert_metric_name: false

    monitor: val/mAP
    mode: max
    # save_top_k: 5
    # save_last: true
    every_n_epochs: 1
